services:
  hw1:
    image: "mongo:7.0.12-rc1-jammy"
    container_name: "hw1"
    hostname: "hw1"
    ports:
      - "27024:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    restart: always
    healthcheck:
      test: echo 'db.runCommand({find:"hw1.courses"}).ok' | mongosh --authenticationDatabase admin --host localhost -u admin -p 1234 admin --quiet | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - course_mongodb_data_vol2:/data/db/
      - course_mongodb_log_vol2:/var/log/mongodb/
    networks:
      - course_mongodb_net
  course-elearning-homework1:
    build: .
    image: "course-elearning-homework1"
    container_name: "course-elearning-homework1"
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      hw1:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - course_mongodb_net

volumes:
  course_mongodb_data_vol2:
  course_mongodb_log_vol2:

networks:
  course_mongodb_net: