spring:
  application:
    name: course-elearning-homework1
  data:
    mongodb:
      uri: mongodb://admin:1234@localhost:27024/
      database: hw1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://admin:1234@hw1:27017/
      database: hw1
